#![no_std]

//! ProofOfVaultVerifier — Groth16 / BLS12-381 on-chain verifier for Propulsor
//!
//! Verifies that a user's vault_2 balance satisfies a threshold, without
//! revealing the exact balance. The circuit is proof_of_vault (Circom/BLS12-381).
//!
//! Groth16 verification equation:
//!   e(-A, B) · e(α, β) · e(vk_x, γ) · e(C, δ) == 1
//!
//! Where vk_x = ic[0] + ic[1]·threshold (one public input: the threshold).
//! Client pre-negates A to avoid implementing g1_neg in the contract.
//!
//! Deploy:
//!   stellar contract deploy \
//!     --wasm target/wasm32v1-none/release/proof_of_vault_verifier.wasm \
//!     --source deployer --network testnet

use soroban_sdk::{
    contract, contractimpl, contracttype, contracterror, panic_with_error,
    Address, Bytes, BytesN, Env, Symbol, Vec,
    crypto::bls12_381::{G1Affine, G2Affine, Fr},
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LEDGER_THRESHOLD: u32 = 518_400;    // 30 days
const LEDGER_EXTEND_TO: u32 = 3_110_400;  // 180 days

// Threshold bounds in USDC stroops (7 decimals): $0.01 – $1,000,000
const THRESHOLD_MIN: i128 = 100_000;            // $0.01 USDC
const THRESHOLD_MAX: i128 = 10_000_000_000_000; // $1,000,000 USDC

// ---------------------------------------------------------------------------
// Data structures
// ---------------------------------------------------------------------------

/// Groth16 proof points. Client pre-negates A (neg_A) before calling.
/// Encoding: uncompressed big-endian (matches snarkjs/IETF BLS12-381).
#[contracttype]
#[derive(Clone)]
pub struct Proof {
    pub a: BytesN<96>,    // neg_A (pre-negated by client)
    pub b: BytesN<192>,
    pub c: BytesN<96>,
}

/// Verification key for proof_of_vault (1 public input: threshold).
/// Generated by `snarkjs zkey export verificationkey` + encode_vk.ts.
#[contracttype]
#[derive(Clone)]
pub struct VerificationKey {
    pub alpha: BytesN<96>,
    pub beta:  BytesN<192>,
    pub gamma: BytesN<192>,
    pub delta: BytesN<192>,
    pub ic_0:  BytesN<96>,
    pub ic_1:  BytesN<96>,
}

/// Record stored for each accepted proof.
#[contracttype]
#[derive(Clone)]
pub struct ProofRecord {
    pub user:           Address,
    pub threshold_usdc: i128,  // USDC base units (7 decimals), e.g. 50_0000000 = $50
    pub ledger:         u32,
}

#[contracttype]
pub enum DataKey {
    Vk,
    Admin,
    Nullifier(BytesN<32>), // sha256(neg_a||b||c) → ProofRecord
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[contracterror]
#[derive(Copy, Clone, PartialEq)]
pub enum VerifierError {
    NotInitialized   = 2,
    InvalidProof     = 3,
    ReplayAttack     = 4,
    InvalidThreshold = 5,
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

#[contract]
pub struct ProofOfVaultVerifier;

#[contractimpl]
impl ProofOfVaultVerifier {

    // ── Constructor (Protocol 22+) ─────────────────────────────────────────

    /// Called once at deploy time. Sets admin and VK atomically — no race window.
    pub fn __constructor(env: Env, admin: Address, vk: VerificationKey) {
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Vk, &vk);
        env.storage().instance().extend_ttl(LEDGER_THRESHOLD, LEDGER_EXTEND_TO);
    }

    // ── Core verification ──────────────────────────────────────────────────

    /// Verify a Groth16/BLS12-381 range proof and store the result on-chain.
    ///
    /// Parameters:
    ///   user      — the account making the claim (must sign)
    ///   proof     — neg_a (pre-negated), b, c points
    ///   threshold — Fr scalar: public threshold in USDC stroops (32-byte big-endian)
    ///
    /// Returns the nullifier (sha256 of proof bytes) — use as proof_hash in the UI.
    pub fn verify_proof(
        env: Env,
        user: Address,
        proof: Proof,
        threshold_bytes: BytesN<32>,
    ) -> BytesN<32> {
        user.require_auth();

        // Validate threshold semantics: [$0.01, $1,000,000] USDC
        let threshold_usdc = Self::fr_bytes_to_i128(&threshold_bytes.to_array());
        if threshold_usdc < THRESHOLD_MIN || threshold_usdc > THRESHOLD_MAX {
            panic_with_error!(&env, VerifierError::InvalidThreshold);
        }

        // Load VK
        let vk: VerificationKey = env.storage().instance()
            .get(&DataKey::Vk)
            .unwrap_or_else(|| panic_with_error!(&env, VerifierError::NotInitialized));

        // ── Replay protection ─────────────────────────────────────────────
        // Nullifier = sha256(neg_a || b || c) — unique per proof
        let mut proof_bytes = Bytes::new(&env);
        proof_bytes.extend_from_array(&proof.a.to_array());
        proof_bytes.extend_from_array(&proof.b.to_array());
        proof_bytes.extend_from_array(&proof.c.to_array());
        let nullifier: BytesN<32> = env.crypto().sha256(&proof_bytes).into();

        if env.storage().persistent().has(&DataKey::Nullifier(nullifier.clone())) {
            panic_with_error!(&env, VerifierError::ReplayAttack);
        }

        // ── Groth16 verification ──────────────────────────────────────────
        let bls = env.crypto().bls12_381();

        // vk_x = ic_0 + ic_1 * threshold
        let threshold_fr = Fr::from_bytes(threshold_bytes.clone());
        let ic_0         = G1Affine::from_bytes(vk.ic_0.clone());
        let ic_1         = G1Affine::from_bytes(vk.ic_1.clone());
        let ic_1_scaled  = bls.g1_mul(&ic_1, &threshold_fr);
        let vk_x         = bls.g1_add(&ic_0, &ic_1_scaled);

        // e(-A, B) · e(α, β) · e(vk_x, γ) · e(C, δ) == 1
        let neg_a = G1Affine::from_bytes(proof.a.clone());
        let b     = G2Affine::from_bytes(proof.b.clone());
        let alpha = G1Affine::from_bytes(vk.alpha.clone());
        let beta  = G2Affine::from_bytes(vk.beta.clone());
        let gamma = G2Affine::from_bytes(vk.gamma.clone());
        let delta = G2Affine::from_bytes(vk.delta.clone());
        let c     = G1Affine::from_bytes(proof.c.clone());

        let g1_points = Vec::from_array(&env, [neg_a, alpha, vk_x, c]);
        let g2_points = Vec::from_array(&env, [b, beta, gamma, delta]);

        if !bls.pairing_check(g1_points, g2_points) {
            panic_with_error!(&env, VerifierError::InvalidProof);
        }

        // ── Persist record ────────────────────────────────────────────────
        let record = ProofRecord {
            user:           user.clone(),
            threshold_usdc,
            ledger:         env.ledger().sequence(),
        };

        env.storage().persistent().set(&DataKey::Nullifier(nullifier.clone()), &record);
        env.storage().persistent().extend_ttl(
            &DataKey::Nullifier(nullifier.clone()),
            LEDGER_THRESHOLD,
            LEDGER_EXTEND_TO,
        );

        // Emit event for frontend indexing
        env.events().publish(
            (Symbol::new(&env, "ProofVerified"),),
            (user, threshold_usdc, nullifier.clone()),
        );

        nullifier
    }

    // ── Read-only queries ──────────────────────────────────────────────────

    /// Look up a previously accepted proof by its nullifier hash.
    pub fn get_proof(env: Env, nullifier: BytesN<32>) -> Option<ProofRecord> {
        env.storage().persistent().get(&DataKey::Nullifier(nullifier))
    }

    /// True if a nullifier has already been used (replay check for UI).
    pub fn is_used(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage().persistent().has(&DataKey::Nullifier(nullifier))
    }

    // ── Internal helpers ───────────────────────────────────────────────────

    fn fr_bytes_to_i128(bytes: &[u8; 32]) -> i128 {
        let mut buf = [0u8; 16];
        buf.copy_from_slice(&bytes[16..32]);
        i128::from_be_bytes(buf)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Env;

    fn dummy_g1(env: &Env) -> BytesN<96> {
        // BLS12-381 G1 generator point (uncompressed big-endian x || y)
        BytesN::from_array(env, &[
            0x17, 0xf1, 0xd3, 0xa7, 0x31, 0x97, 0xd7, 0x94,
            0x26, 0x95, 0x63, 0x8c, 0x4f, 0xa9, 0xac, 0x0f,
            0xc3, 0x68, 0x8c, 0x4f, 0x97, 0x74, 0xb9, 0x05,
            0xa1, 0x4e, 0x3a, 0x3f, 0x17, 0x1b, 0xac, 0x58,
            0x6c, 0x55, 0xe8, 0x3f, 0xf9, 0x7a, 0x1a, 0xef,
            0xfb, 0x3a, 0xf0, 0x0a, 0xdb, 0x22, 0xc6, 0xbb,
            0x08, 0xb3, 0xf4, 0x81, 0xe3, 0xaa, 0xa0, 0xf1,
            0xa0, 0x9e, 0x30, 0xed, 0x74, 0x1d, 0x8a, 0xe4,
            0xfc, 0xf5, 0xe0, 0x95, 0xd5, 0xd0, 0x0a, 0xf6,
            0x00, 0x01, 0xd3, 0x80, 0x88, 0x03, 0x57, 0x5f,
            0xf0, 0x4f, 0x9f, 0x1c, 0x8f, 0xa2, 0x5c, 0x27,
            0x42, 0x57, 0x26, 0x89, 0x7f, 0x0a, 0x54, 0x02,
        ])
    }

    fn make_vk(env: &Env, g1: BytesN<96>) -> VerificationKey {
        VerificationKey {
            alpha: g1.clone(),
            beta:  BytesN::from_array(env, &[0u8; 192]),
            gamma: BytesN::from_array(env, &[0u8; 192]),
            delta: BytesN::from_array(env, &[0u8; 192]),
            ic_0:  g1.clone(),
            ic_1:  g1.clone(),
        }
    }

    #[test]
    fn test_constructor() {
        let env = Env::default();
        env.mock_all_auths();
        let admin = Address::generate(&env);
        let g1 = dummy_g1(&env);
        let vk = make_vk(&env, g1);
        // soroban-sdk 22: register passes constructor args at deploy time
        let contract_id = env.register(ProofOfVaultVerifier, (admin.clone(), vk.clone()));
        // Verify VK was stored by constructor
        let stored_vk: VerificationKey = env.as_contract(&contract_id, || {
            env.storage().instance().get(&DataKey::Vk).unwrap()
        });
        assert_eq!(stored_vk.alpha, vk.alpha);
    }
}
