/**
 * encode_risc0_vk.ts — Encode RISC Zero's published Groth16 (BN254) verifying
 * key into Soroban/CAP-0074 byte format, ready for
 * ConsistentSavingVerifier.__constructor().
 *
 * Unlike encode_vk.ts (which converts a locally-generated snarkjs
 * verification_key.json for the Proof-of-Vault circuit), this key is NOT
 * generated by Propulsor — it's RISC Zero's own published Groth16 wrapper
 * verifying key (same one risc0-ethereum's on-chain Solidity verifier uses),
 * copied verbatim from risc0/groth16/src/verifier.rs. See
 * zk/risc0/consistent_saving/SPEC.md §2 for the full derivation and citation
 * — do not edit the decimal constants below without re-deriving from source.
 *
 * Byte order: confirmed (SPEC.md §2) that CAP-0074's G2 encoding
 * (be(X_c1) || be(X_c0) || be(Y_c1) || be(Y_c0)) matches RISC Zero's named
 * constant order (X1, X2, Y1, Y2) directly — no c0/c1 swap needed here,
 * unlike encode_vk.ts's g2ToHex (which does need one, for BLS12-381/snarkjs).
 *
 * Usage:
 *   npx tsx scripts/encode_risc0_vk.ts
 *
 * Output: vk_risc0_encoded.json — ready to paste into
 *   ConsistentSavingVerifier.__constructor(admin, vk, image_id)
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
const __dirname = dirname(fileURLToPath(import.meta.url));

// ── BN254 Fp element (decimal) → 32-byte big-endian hex ─────────────────────
function fpToHex(decimal: string): string {
  return BigInt(decimal).toString(16).padStart(64, "0");
}

// G1 = be(X) || be(Y) — 64 bytes. CAP-0074 §"G1" encoding rule.
function g1ToHex(x: string, y: string): string {
  return fpToHex(x) + fpToHex(y);
}

// G2 = be(X_c1) || be(X_c0) || be(Y_c1) || be(Y_c0) — 128 bytes.
// Confirmed equal to source's printed (X1, X2, Y1, Y2) order — see SPEC.md §2.
function g2ToHex(x1: string, x2: string, y1: string, y2: string): string {
  return fpToHex(x1) + fpToHex(x2) + fpToHex(y1) + fpToHex(y2);
}

// ── RISC Zero's published Groth16 VK (risc0-zkvm 3.0.6 / risc0-groth16 3.0.5) ──
// Source: https://github.com/risc0/risc0/blob/main/risc0/groth16/src/verifier.rs
// "Constants from: risc0-ethereum/contracts/src/groth16/Groth16Verifier.sol"
const alpha = g1ToHex(
  "20491192805390485299153009773594534940189261866228447918068658471970481763042",
  "9383485363053290200918347156157836566562967994039712273449902621266178545958",
);

const beta = g2ToHex(
  "4252822878758300859123897981450591353533073413197771768651442665752259397132",
  "6375614351688725206403948262868962793625744043794305715222011528459656738731",
  "21847035105528745403288232691147584728191162732299865338377159692350059136679",
  "10505242626370262277552901082094356697409835680220590971873171140371331206856",
);

const gamma = g2ToHex(
  "11559732032986387107991004021392285783925812861821192530917403151452391805634",
  "10857046999023057135944570762232829481370756359578518086990519993285655852781",
  "4082367875863433681332203403145435568316851327593401208105741076214120093531",
  "8495653923123431417604973247489272438418190587263600148770280649306958101930",
);

const delta = g2ToHex(
  "1668323501672964604911431804142266013250380587483576094566949227275849579036",
  "12043754404802191763554326994664886008979042643626290185762540825416902247219",
  "7710631539206257456743780535472368339139328733484942210876916214502466455394",
  "13740680757317479711909903993315946540841369848973133181051452051592786724563",
);

// gamma_abc_g1 / IC — 6 points (1 constant term + 5 public inputs). See
// SPEC.md §3 for what the 5 public inputs are (they are NOT the raw journal).
const ic = [
  g1ToHex(
    "8446592859352799428420270221449902464741693648963397251242447530457567083492",
    "1064796367193003797175961162477173481551615790032213185848276823815288302804",
  ),
  g1ToHex(
    "3179835575189816632597428042194253779818690147323192973511715175294048485951",
    "20895841676865356752879376687052266198216014795822152491318012491767775979074",
  ),
  g1ToHex(
    "5332723250224941161709478398807683311971555792614491788690328996478511465287",
    "21199491073419440416471372042641226693637837098357067793586556692319371762571",
  ),
  g1ToHex(
    "12457994489566736295787256452575216703923664299075106359829199968023158780583",
    "19706766271952591897761291684837117091856807401404423804318744964752784280790",
  ),
  g1ToHex(
    "19617808913178163826953378459323299110911217259216006187355745713323154132237",
    "21663537384585072695701846972542344484111393047775983928357046779215877070466",
  ),
  g1ToHex(
    "6834578911681792552110317589222010969491336870276623105249474534788043166867",
    "15060583660288623605191393599883223885678013570733629274538391874953353488393",
  ),
];

const encoded = {
  alpha,
  beta,
  gamma,
  delta,
  ic_0: ic[0],
  ic_1: ic[1],
  ic_2: ic[2],
  ic_3: ic[3],
  ic_4: ic[4],
  ic_5: ic[5],
};

const outPath = join(__dirname, "vk_risc0_encoded.json");
writeFileSync(outPath, JSON.stringify(encoded, null, 2));

console.log("✓ RISC Zero Groth16 VK encoded and written to vk_risc0_encoded.json");
console.log(
  "\nStill needed before deploying ConsistentSavingVerifier: the fixed public-input",
);
console.log(
  "constants derived from ALLOWED_CONTROL_ROOT / BN254_IDENTITY_CONTROL_ID — see",
);
console.log(
  "zk/risc0/consistent_saving/host/examples/crosscheck_fixture.rs, which prints them",
);
console.log("after an empirical cross-check against a real Groth16 receipt.");
